### ISSUE TITLE
the `0x` prefix

### ISSUE THREAD

**Issue by wanderer** [ethereum/ethereumjs-util#5]
Should we accept the zero hex prefix? 

One big problem is pretty much all the function in all of ethereumjs-* assume arguments as a buffer (or an uint8 array) or a hex string. Since i assume all strings are hex strings, i don't need the 0x prefix and therefore don't process it (with the exception of the schema fields). If we added '0x' to parsing we will have to make sure that all the function in ethereumjs-*  will be able to accept them. The other option is to let the users handle it. We provide a [stripHexprefixString](https://github.com/ethereum/ethereumjs-util#striphexprefixstring) to make this easy.

related #4

**Comment by wanderer** [comment]
@frozeman @kumavis @ethers

**Comment by frozeman** [comment]
if you expect HEX, it should also be compatible with 0x.. strings, otherwise people make unecessary mistakes.

Be flexible in the input and strict in the output ;)

**Comment by kumavis** [comment]
i think most of the ecosystem is all up on that unnecesary 0x, so we should strip it

**Comment by wanderer** [comment]
k, votes are in and talled. we strip.

**Comment by wanderer** [comment]
ok ethereumjs-util now strips, next up rlp and merkle tries

**Comment by frozeman** [comment]
is this already released?

**Comment by wanderer** [comment]
Nope, Ill release today after I convert RLP over.  Because ethereumjs-util
exposes rlp

**Comment by wanderer** [comment]
@frozeman ok this is now done in 1.5.1

**Comment by ethers** [comment]
+1
